# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 52770a01c603d02b457ead611c6c3b5af5dc453985168954944f8b37c665cdc5a6857d582f403e3f282b550f49ab3434c3bad9eaf91e1f955f9674f6d5f589e7

test:
  secret_key_base: 3e344356af9c987d51211abc66f05c7a24bac6eab2442eac393919ced1ea5de72a6cd4ecf47f9da62a4f7c05a76da31d5ee288da73eb7d2471b9b6136d6fc9b0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
